import Head from "next/head";
import React, { Fragment } from "react";
import Footer from "./Footer";
import Header from "./Header";

const Layout = ({children, title="Ecommerce"}) => {
     //console.log("layout", title)
  return (
    <Fragment>
      
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Header />
          {children}
        <Footer />

    </Fragment>
  );
};

export default Layout;
